# Generated by Django 2.2.5 on 2019-09-29 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='заголовок объекта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание объекта')),
                ('sort', models.IntegerField(blank=True, default=0, verbose_name='номер объекта для сортировки')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='активен ли объект')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='обновлен')),
            ],
            options={
                'verbose_name': 'Ядро',
                'verbose_name_plural': 'Ядра',
                'ordering': ('-is_active', 'sort', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('core_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.Core')),
            ],
            bases=('mainapp.core',),
        ),
        migrations.CreateModel(
            name='PetCharacter',
            fields=[
                ('core_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.Core')),
            ],
            bases=('mainapp.core',),
        ),
        migrations.CreateModel(
            name='PetColor',
            fields=[
                ('core_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.Core')),
            ],
            bases=('mainapp.core',),
        ),
        migrations.CreateModel(
            name='PetGender',
            fields=[
                ('core_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.Core')),
            ],
            bases=('mainapp.core',),
        ),
        migrations.CreateModel(
            name='PetSize',
            fields=[
                ('core_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.Core')),
            ],
            bases=('mainapp.core',),
        ),
        migrations.CreateModel(
            name='PetWool',
            fields=[
                ('core_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.Core')),
            ],
            bases=('mainapp.core',),
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('core_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.Core')),
                ('image', models.ImageField(upload_to='images')),
                ('related_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mainapp.Core', verbose_name='изображения')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
                'ordering': ('sort', 'updated'),
            },
            bases=('mainapp.core',),
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('core_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.Core')),
                ('age', models.PositiveIntegerField(default=0, verbose_name='возраст (лет)')),
                ('month', models.PositiveIntegerField(default=0, verbose_name='возраст (мес)')),
                ('pet_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Category')),
                ('pet_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.PetCharacter')),
                ('pet_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.PetColor')),
                ('pet_gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.PetGender')),
                ('pet_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.PetSize')),
                ('pet_wool_length', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.PetWool')),
            ],
            bases=('mainapp.core',),
        ),
    ]
