<<<<<<< HEAD
=======
<<<<<<< HEAD
>>>>>>> test_2
<<<<<<< HEAD
# Generated by Django 2.2.5 on 2019-09-29 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='заголовок объекта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание объекта')),
                ('sort', models.IntegerField(blank=True, default=0, verbose_name='номер объекта для сортировки')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='активен ли объект')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='обновлен')),
            ],
            options={
                'verbose_name': 'Ядро',
                'verbose_name_plural': 'Ядра',
                'ordering': ('-is_active', 'sort', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('core_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.Core')),
            ],
            bases=('mainapp.core',),
        ),
        migrations.CreateModel(
            name='PetCharacter',
            fields=[
                ('core_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.Core')),
            ],
            bases=('mainapp.core',),
        ),
        migrations.CreateModel(
            name='PetColor',
            fields=[
                ('core_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.Core')),
            ],
            bases=('mainapp.core',),
        ),
        migrations.CreateModel(
            name='PetGender',
            fields=[
                ('core_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.Core')),
            ],
            bases=('mainapp.core',),
        ),
        migrations.CreateModel(
            name='PetSize',
            fields=[
                ('core_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.Core')),
            ],
            bases=('mainapp.core',),
        ),
        migrations.CreateModel(
            name='PetWool',
            fields=[
                ('core_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.Core')),
            ],
            bases=('mainapp.core',),
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('core_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.Core')),
                ('image', models.ImageField(upload_to='images')),
                ('related_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mainapp.Core', verbose_name='изображения')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
                'ordering': ('sort', 'updated'),
            },
            bases=('mainapp.core',),
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('core_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.Core')),
                ('age', models.PositiveIntegerField(default=0, verbose_name='возраст (лет)')),
                ('month', models.PositiveIntegerField(default=0, verbose_name='возраст (мес)')),
                ('pet_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Category')),
                ('pet_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.PetCharacter')),
                ('pet_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.PetColor')),
                ('pet_gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.PetGender')),
                ('pet_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.PetSize')),
                ('pet_wool_length', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.PetWool')),
            ],
            bases=('mainapp.core',),
        ),
    ]
=======
<<<<<<< HEAD
=======
=======
>>>>>>> 2109c366bd5217a5d617f7aeecd5fe4365dd5632
>>>>>>> test_2
# Generated by Django 2.2.4 on 2019-10-01 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='заголовок объекта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание объекта')),
                ('sort', models.IntegerField(blank=True, default=0, verbose_name='номер объекта для сортировки')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='активен ли объект')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='обновлен')),
            ],
            options={
                'verbose_name': 'Ядро',
                'verbose_name_plural': 'Ядра',
                'ordering': ('-is_active', 'sort', 'name'),
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('core_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.Core')),
            ],
            bases=('mainapp.core',),
        ),
        migrations.CreateModel(
            name='PetBreed',
            fields=[
                ('core_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.Core')),
            ],
            bases=('mainapp.core',),
        ),
        migrations.CreateModel(
            name='PetCategory',
            fields=[
                ('core_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.Core')),
            ],
            bases=('mainapp.core',),
        ),
        migrations.CreateModel(
            name='PetCharacter',
            fields=[
                ('core_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.Core')),
            ],
            bases=('mainapp.core',),
        ),
        migrations.CreateModel(
            name='PetColor',
            fields=[
                ('core_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.Core')),
            ],
            bases=('mainapp.core',),
        ),
        migrations.CreateModel(
            name='PetGender',
            fields=[
                ('core_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.Core')),
            ],
            bases=('mainapp.core',),
        ),
        migrations.CreateModel(
            name='PetSize',
            fields=[
                ('core_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.Core')),
            ],
            bases=('mainapp.core',),
        ),
        migrations.CreateModel(
            name='PetStatus',
            fields=[
                ('core_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.Core')),
            ],
            bases=('mainapp.core',),
        ),
        migrations.CreateModel(
            name='PetWool',
            fields=[
                ('core_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.Core')),
            ],
            bases=('mainapp.core',),
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('core_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.Core')),
                ('shelter_logo', models.ImageField(blank=True, upload_to='shelter/images', verbose_name='логотип приюта')),
                ('shelter_address', models.CharField(max_length=255, unique=True, verbose_name='адрес')),
                ('shelter_phone', models.CharField(max_length=17, unique=True, verbose_name='телефон')),
                ('shelter_email', models.EmailField(max_length=254, unique=True, verbose_name='эл.почта')),
                ('shelter_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shelters', to='mainapp.City', verbose_name='город')),
            ],
            bases=('mainapp.core',),
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('core_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.Core')),
                ('link', models.URLField(blank=True, null=True, unique=True, verbose_name='ссылка на соц.сеть')),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='links', to='mainapp.Shelter')),
            ],
            bases=('mainapp.core',),
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('core_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.Core')),
                ('image', models.ImageField(upload_to='images')),
                ('related_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mainapp.Core', verbose_name='изображения')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
                'ordering': ('sort', 'updated'),
            },
            bases=('mainapp.core',),
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('core_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.Core')),
                ('age', models.PositiveIntegerField(default=0, verbose_name='возраст (лет)')),
                ('month', models.PositiveIntegerField(default=0, verbose_name='возраст (мес)')),
                ('pet_breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.PetBreed')),
                ('pet_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.PetCategory')),
                ('pet_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.PetCharacter')),
                ('pet_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.PetColor')),
                ('pet_gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.PetGender')),
                ('pet_shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='mainapp.Shelter')),
                ('pet_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.PetSize')),
                ('pet_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.PetStatus')),
                ('pet_wool_length', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.PetWool')),
            ],
            bases=('mainapp.core',),
        ),
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('core_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.Core')),
                ('account', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='mainapp.Shelter', verbose_name='реквизиты счетов')),
            ],
            bases=('mainapp.core',),
        ),
    ]
>>>>>>> 12ae91e2b198bcec6a9f6c3821aa7d75bb9ca638
