# Generated by Django 2.2.4 on 2019-09-30 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_health',
            fields=[
                ('core_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.Core')),
            ],
            bases=('mainapp.core',),
        ),
        migrations.CreateModel(
            name='Category_type',
            fields=[
                ('core_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.Core')),
            ],
            bases=('mainapp.core',),
        ),
        migrations.CreateModel(
            name='PetCity',
            fields=[
                ('core_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.Core')),
            ],
            bases=('mainapp.core',),
        ),
        migrations.RemoveField(
            model_name='pet',
            name='pet_category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_category_health',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Category_health'),
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_category_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Category_type'),
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.PetCity'),
        ),
    ]
